# Code generated by generate_api.py. DO NOT EDIT.
"""API 请求/响应 TypedDict（完整嵌套字段，与 api-definitions.json 一致）。"""

from typing import Any, Dict, List

from typing_extensions import NotRequired, Required, TypedDict

class ExaminingConfigRequest(TypedDict):
    template_id: Required[int]


class ExaminingConfigResponseDataFirstExaminingListSecondExaminingListThirdExaminingListSubExaminingList(TypedDict):
    radio: Required[List[str]]
    checkbox: Required[List[str]]


class ExaminingConfigResponseDataFirstExaminingListSecondExaminingListThirdExaminingListItem(TypedDict):
    key: Required[str]
    title: Required[str]
    type: Required[str]
    second_examining_category_id: Required[int]
    sub_examining_list: Required[ExaminingConfigResponseDataFirstExaminingListSecondExaminingListThirdExaminingListSubExaminingList]


class ExaminingConfigResponseDataFirstExaminingListSecondExaminingListItem(TypedDict):
    key: Required[str]
    title: Required[str]
    type: Required[str]
    options: Required[List[str]]
    third_examining_list: Required[List[ExaminingConfigResponseDataFirstExaminingListSecondExaminingListThirdExaminingListItem]]


class ExaminingConfigResponseDataFirstExaminingListItem(TypedDict):
    key: Required[str]
    title: Required[str]
    second_examining_list: Required[List[ExaminingConfigResponseDataFirstExaminingListSecondExaminingListItem]]


class ExaminingConfigResponseData(TypedDict):
    first_examining_list: Required[List[ExaminingConfigResponseDataFirstExaminingListItem]]


class ExaminingConfigResponse(TypedDict):
    data: Required[ExaminingConfigResponseData]


class ImeiQueryRequest(TypedDict):
    imei: Required[str]


class ImeiQueryResponseData(TypedDict):
    status: Required[int]


class ImeiQueryResponse(TypedDict):
    data: Required[ImeiQueryResponseData]


class DigitalSuperSaleRequestAddress(TypedDict):
    province: Required[str]
    city: Required[str]
    county: Required[str]
    street: Required[str]
    name: Required[str]
    mobile: Required[str]


class DigitalSuperSaleRequestExaminingListSecondExaminingListThirdExaminingListItem(TypedDict):
    key: Required[str]
    value: Required[str]
    imgs: NotRequired[List[str]]
    status: Required[bool]


class DigitalSuperSaleRequestExaminingListSecondExaminingListItem(TypedDict):
    key: Required[str]
    value: Required[str]
    third_examining_list: NotRequired[List[DigitalSuperSaleRequestExaminingListSecondExaminingListThirdExaminingListItem]]


class DigitalSuperSaleRequestExaminingListItem(TypedDict):
    key: Required[str]
    second_examining_list: Required[List[DigitalSuperSaleRequestExaminingListSecondExaminingListItem]]


class DigitalSuperSaleRequest(TypedDict):
    goods_sn: Required[str]
    sku_id: Required[int]
    quality: Required[int]
    address: Required[DigitalSuperSaleRequestAddress]
    imei: Required[str]
    price: Required[int]
    general_imgs: Required[List[str]]
    flaw_imgs: NotRequired[List[str]]
    examining_list: Required[List[DigitalSuperSaleRequestExaminingListItem]]
    result_desc: Required[str]
    template_id: Required[int]
    internal_enterprise_id: NotRequired[str]
    product_source_type: NotRequired[int]


class DigitalSuperSaleResponseData(TypedDict):
    result: Required[bool]


class DigitalSuperSaleResponse(TypedDict):
    data: Required[DigitalSuperSaleResponseData]


class DigitalSuperSaleV2RequestAddress(TypedDict):
    province: Required[str]
    city: Required[str]
    county: Required[str]
    street: Required[str]
    name: Required[str]
    mobile: Required[str]


class DigitalSuperSaleV2RequestExaminingListItem(TypedDict):
    key: Required[str]
    imgs: NotRequired[List[str]]


class DigitalSuperSaleV2Request(TypedDict):
    goods_sn: Required[str]
    sku_id: Required[int]
    quality: Required[str]
    address: Required[DigitalSuperSaleV2RequestAddress]
    imei: Required[str]
    price: Required[int]
    general_imgs: Required[List[str]]
    flaw_imgs: NotRequired[List[str]]
    examining_list: Required[List[DigitalSuperSaleV2RequestExaminingListItem]]
    result_desc: Required[str]


class DigitalSuperSaleV2ResponseData(TypedDict):
    result: Required[bool]


class DigitalSuperSaleV2Response(TypedDict):
    data: Required[DigitalSuperSaleV2ResponseData]


class InspectSignReceiptRequest(TypedDict):
    express_number: Required[str]


class InspectSignReceiptResponseData(TypedDict):
    status: Required[int]


class InspectSignReceiptResponse(TypedDict):
    data: Required[InspectSignReceiptResponseData]


class BindCertificateBuckleRequest(TypedDict):
    erpSkuId: NotRequired[str]
    antiFakeCode: NotRequired[str]
    certificateNo: NotRequired[str]


class BindCertificateBuckleResponseData(TypedDict):
    data: Required[bool]


class BindCertificateBuckleResponse(TypedDict):
    data: Required[BindCertificateBuckleResponseData]


class InventorySyncRequestDetailItem(TypedDict):
    merchant_sku_code: Required[str]
    sku_id: Required[int]
    qty: NotRequired[int]
    lock_qty: NotRequired[int]
    salable_qty: Required[int]
    batch_id: NotRequired[str]
    expire_date: NotRequired[str]
    production_date: NotRequired[str]
    mapping_type: NotRequired[int]
    is_new: NotRequired[int]


class InventorySyncRequest(TypedDict):
    detail: Required[List[InventorySyncRequestDetailItem]]


class InventorySyncResponseDataSuccListItem(TypedDict):
    merchant_code: Required[str]
    code: Required[int]
    msg: Required[str]


class InventorySyncResponseDataFailListItem(TypedDict):
    merchant_code: Required[str]
    code: Required[int]
    msg: Required[str]


class InventorySyncResponseData(TypedDict):
    sync_result: Required[bool]
    succ_list: Required[List[InventorySyncResponseDataSuccListItem]]
    fail_list: Required[List[InventorySyncResponseDataFailListItem]]


class InventorySyncResponse(TypedDict):
    data: Required[InventorySyncResponseData]


class InventoryListRequestDetailItem(TypedDict):
    merchant_sku_code: Required[str]
    sku_id: NotRequired[int]


class InventoryListRequest(TypedDict):
    detail: Required[List[InventoryListRequestDetailItem]]


class InventoryListResponseDataDetailItem(TypedDict):
    available_qty: Required[int]
    lock_qty: Required[int]
    external_salable_qty: Required[int]
    merchant_sku_code: Required[str]
    sku_id: Required[int]


class InventoryListResponseData(TypedDict):
    detail: Required[List[InventoryListResponseDataDetailItem]]


class InventoryListResponse(TypedDict):
    data: Required[InventoryListResponseData]


class UpdateStockRequest(TypedDict):
    goods_sn: Required[str]
    stock: Required[int]


class UpdateStockResponse(TypedDict):
    status: Required[int]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class DeliveryBizRequestSendAddress(TypedDict):
    name: Required[str]
    province: Required[str]
    city: Required[str]
    county: Required[str]
    mobile: Required[str]
    street: NotRequired[str]


class DeliveryBizRequest(TypedDict):
    order_number: Required[str]
    send_address: Required[DeliveryBizRequestSendAddress]


class DeliveryBizResponseDataListItem(TypedDict):
    order_number: Required[str]
    express_number: Required[str]
    express_name: Required[str]
    two_dimension_code: Required[str]
    dimension_code: Required[str]
    dest_route_label: Required[str]
    dept_code: Required[str]
    address_info: Required[Any]
    goods_title: Required[str]


class DeliveryBizResponseData(TypedDict):
    list: Required[List[DeliveryBizResponseDataListItem]]


class DeliveryBizResponse(TypedDict):
    data: Required[DeliveryBizResponseData]


class ConsignPlatformDeliveryRequestAddress(TypedDict):
    province: NotRequired[str]
    city: NotRequired[str]
    county: NotRequired[str]
    street: NotRequired[str]
    name: NotRequired[str]
    mobile: NotRequired[str]
    region: NotRequired[str]


class ConsignPlatformDeliveryRequest(TypedDict):
    goods_sn: Required[str]
    internal_enterprise_id: NotRequired[str]
    imei: NotRequired[str]
    address: NotRequired[ConsignPlatformDeliveryRequestAddress]


class ConsignPlatformDeliveryResponseDataAddressInfo(TypedDict):
    province: Required[str]
    city: Required[str]
    county: Required[str]
    street: Required[str]
    name: Required[str]
    mobile: Required[str]


class ConsignPlatformDeliveryResponseData(TypedDict):
    express_number: Required[str]
    express_name: Required[str]
    express_type: Required[str]
    dept_code: Required[str]
    goods_category_name: Required[str]
    road: Required[str]
    express_product_type: Required[str]
    source_center_name: Required[str]
    target_center_name: Required[str]
    site_name: Required[str]
    source_code: Required[str]
    target_code: Required[str]
    two_dimension_code: Required[str]
    dimension_code: Required[str]
    origin_express_number: Required[str]
    generate_time: Required[str]
    generate_tip: Required[str]
    dest_route_label: Required[str]
    address_info: Required[ConsignPlatformDeliveryResponseDataAddressInfo]


class ConsignPlatformDeliveryResponse(TypedDict):
    data: Required[ConsignPlatformDeliveryResponseData]


class SaveExpressNumberRequestAddress(TypedDict):
    province: NotRequired[str]
    city: NotRequired[str]
    county: NotRequired[str]
    street: NotRequired[str]
    name: NotRequired[str]
    mobile: NotRequired[str]
    region: NotRequired[str]


class SaveExpressNumberRequest(TypedDict):
    goods_sn: Required[str]
    express_number: Required[str]
    express_type: Required[int]
    address: NotRequired[SaveExpressNumberRequestAddress]


class SaveExpressNumberResponse(TypedDict):
    status: Required[int]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class InspectLogisticsQueryRequestAddress(TypedDict):
    province: NotRequired[str]
    city: NotRequired[str]
    county: NotRequired[str]
    street: NotRequired[str]
    name: NotRequired[str]
    mobile: NotRequired[str]
    region: NotRequired[str]


class InspectLogisticsQueryRequest(TypedDict):
    goods_sn_arr: Required[List[str]]
    express_number: NotRequired[str]
    delivery_method: Required[int]
    express_type: NotRequired[int]
    internal_enterprise_id: NotRequired[str]
    address: NotRequired[InspectLogisticsQueryRequestAddress]


class InspectLogisticsQueryResponseDataAddressInfo(TypedDict):
    name: Required[str]
    mobile: Required[str]
    province: Required[str]
    city: Required[str]
    county: Required[str]
    street: Required[str]


class InspectLogisticsQueryResponseDataSelfPickupInfo(TypedDict):
    self_pickup_title: Required[str]
    merchant_info: Required[str]
    self_pickup_number: Required[str]


class InspectLogisticsQueryResponseDataExpressInfo(TypedDict):
    express_number: Required[str]
    express_name: Required[str]
    express_type: Required[str]
    dept_code: Required[str]
    goods_category_name: Required[str]
    road: NotRequired[str]
    express_product_type: NotRequired[str]
    source_center_name: NotRequired[str]
    target_center_name: NotRequired[str]
    site_name: NotRequired[str]
    source_code: NotRequired[str]
    target_code: NotRequired[str]
    two_dimension_code: NotRequired[str]
    dimension_code: NotRequired[str]
    origin_express_number: NotRequired[str]
    generate_tip: NotRequired[str]
    dest_route_label: NotRequired[str]


class InspectLogisticsQueryResponseData(TypedDict):
    delivery_method: Required[int]
    total: Required[int]
    generate_time: Required[str]
    address_info: Required[InspectLogisticsQueryResponseDataAddressInfo]
    self_pickup_info: NotRequired[InspectLogisticsQueryResponseDataSelfPickupInfo]
    express_info: NotRequired[InspectLogisticsQueryResponseDataExpressInfo]


class InspectLogisticsQueryResponse(TypedDict):
    data: Required[InspectLogisticsQueryResponseData]


class PostVerificationWarehouseInfoRequest(TypedDict):
    rule_id: Required[int]


class PostVerificationWarehouseInfoResponseDataAddress(TypedDict):
    province: Required[str]
    city: Required[str]
    county: Required[str]
    street: Required[str]
    name: Required[str]
    mobile: Required[str]
    region: Required[str]


class PostVerificationWarehouseInfoResponseData(TypedDict):
    address: Required[PostVerificationWarehouseInfoResponseDataAddress]


class PostVerificationWarehouseInfoResponse(TypedDict):
    data: Required[PostVerificationWarehouseInfoResponseData]


class DeliveryConfirmRequest(TypedDict):
    order_number: Required[str]
    express_number: Required[str]
    address: NotRequired[Any]


class DeliveryConfirmResponseData(TypedDict):
    result: Required[bool]


class DeliveryConfirmResponse(TypedDict):
    data: Required[DeliveryConfirmResponseData]


class LogisticsQueryRequest(TypedDict):
    express_number: Required[str]
    is_reverse: NotRequired[bool]


class LogisticsQueryResponseDataItemsItem(TypedDict):
    desc: Required[str]
    time: Required[str]
    location: Required[Dict[str, Any]]


class LogisticsQueryResponseData(TypedDict):
    items: Required[List[LogisticsQueryResponseDataItemsItem]]


class LogisticsQueryResponse(TypedDict):
    data: Required[LogisticsQueryResponseData]


class SendSmsRequest(TypedDict):
    mobile: Required[str]


class SendSmsResponse(TypedDict):
    status: Required[int]
    req_id: Required[str]
    data: Required[Dict[str, Any]]


class CheckSmsRequest(TypedDict):
    mobile: Required[str]
    captcha: Required[str]


class CheckSmsResponseData(TypedDict):
    hearder_name: Required[str]
    secret_key: Required[str]


class CheckSmsResponse(TypedDict):
    status: Required[int]
    data: Required[CheckSmsResponseData]


class ConsignOrderInfoRequest(TypedDict):
    upc: NotRequired[str]
    order_number: NotRequired[List[str]]
    batch_number: NotRequired[str]
    page: NotRequired[int]
    page_size: NotRequired[int]
    goods_sn: NotRequired[str]
    is_fee_detail: NotRequired[int]
    is_retrieve: NotRequired[int]


class ConsignOrderInfoResponseDataOrderListGoodsInfo(TypedDict):
    img: Required[str]
    title: Required[str]
    root_category_name: Required[str]
    child_category_name: Required[str]
    property_value: Required[str]
    size: Required[str]
    brand_name: Required[str]
    quality: Required[str]
    status: Required[int]


class ConsignOrderInfoResponseDataOrderListFeeDetail(TypedDict):
    total_fees: Required[int]
    is_activity: Required[int]


class ConsignOrderInfoResponseDataOrderListFreeShipInfo(TypedDict):
    origin_freight: Required[int]
    allowance_price: Required[int]
    seller_freight_price: Required[int]


class ConsignOrderInfoResponseDataOrderListFlawListItem(TypedDict):
    img: Required[str]
    desc: Required[str]


class ConsignOrderInfoResponseDataOrderListItem(TypedDict):
    sell_order_number: Required[str]
    upc: Required[str]
    goods_info: Required[ConsignOrderInfoResponseDataOrderListGoodsInfo]
    status: Required[int]
    sub_status: Required[int]
    status_desc: Required[str]
    sku_min_price: Required[int]
    price: Required[int]
    final_price: Required[int]
    total_fees: Required[int]
    fee_detail: Required[ConsignOrderInfoResponseDataOrderListFeeDetail]
    retrieve_price: Required[int]
    is_free_ship: Required[int]
    free_ship_info: Required[ConsignOrderInfoResponseDataOrderListFreeShipInfo]
    publish_time: Required[str]
    img_list: Required[List[str]]
    flaw_list: Required[List[ConsignOrderInfoResponseDataOrderListFlawListItem]]
    batch_number: Required[str]
    goods_sn: Required[str]
    imei: Required[str]
    buyer_price: Required[int]
    seller_coupon_amount: Required[int]
    full_reduction_amount: Required[int]
    free_shipping_amount: Required[int]
    is_posterior: Required[bool]
    posterior_status: Required[int]
    promotion_info_list: Required[List[Any]]
    bill_price: Required[int]
    buyer_pay_time: Required[str]
    buyer_create_time: Required[str]
    buyer_order_number: Required[str]


class ConsignOrderInfoResponseData(TypedDict):
    order_list: Required[List[ConsignOrderInfoResponseDataOrderListItem]]


class ConsignOrderInfoResponse(TypedDict):
    data: Required[ConsignOrderInfoResponseData]


class BuyerAddressRequest(TypedDict):
    order_number: Required[str]


class BuyerAddressResponseData(TypedDict):
    address: Required[str]


class BuyerAddressResponse(TypedDict):
    data: Required[BuyerAddressResponseData]


class ConsignBatchOrderListRequest(TypedDict):
    mother_no: Required[str]
    page: NotRequired[int]
    page_size: NotRequired[int]


class ConsignBatchOrderListResponseDataOrderListItem(TypedDict):
    sell_order_number: Required[str]
    merchant_sku_code: Required[str]
    verification_time: Required[int]
    verification_result: Required[int]
    verification_failure_reason: Required[str]
    verification_failure_image_url: Required[List[str]]


class ConsignBatchOrderListResponseData(TypedDict):
    mother_no: Required[str]
    total_order_count: Required[int]
    verified_order_count: Required[int]
    unverified_order_count: Required[int]
    pending_order_count: Required[int]
    order_list: Required[List[ConsignBatchOrderListResponseDataOrderListItem]]


class ConsignBatchOrderListResponse(TypedDict):
    data: Required[ConsignBatchOrderListResponseData]


class GetOrderListRequest(TypedDict):
    goods_sn_list: Required[List[str]]


class GetOrderListResponseDataGoodsInfo(TypedDict):
    goods_sn: Required[str]
    title: Required[str]
    code: Required[str]
    price: Required[str]
    brand_id: Required[int]
    brand_name: Required[str]
    size: Required[str]
    desc: Required[str]
    status: Required[int]
    order_status: Required[str]
    stock: Required[int]
    audit_status: Required[int]


class GetOrderListResponseDataBuyerInfo(TypedDict):
    order_number: Required[str]
    buyer_order_number: Required[str]
    pay_time: Required[str]


class GetOrderListResponseDataAddressInfo(TypedDict):
    name: Required[str]
    postcode: Required[str]
    province: Required[str]
    city: Required[str]
    county: Required[str]
    mobile: Required[str]
    region: Required[str]
    street: Required[str]


class GetOrderListResponseDataItem(TypedDict):
    goods_sn: Required[str]
    sell_order_number: Required[str]
    goods_info: Required[GetOrderListResponseDataGoodsInfo]
    buyer_info: Required[GetOrderListResponseDataBuyerInfo]
    address_info: Required[GetOrderListResponseDataAddressInfo]


class GetOrderListResponse(TypedDict):
    data: Required[List[GetOrderListResponseDataItem]]


class MerchantOrderInfoRequest(TypedDict):
    start_update: NotRequired[str]
    end_update: NotRequired[str]
    page: NotRequired[int]
    page_size: NotRequired[int]
    order_number: NotRequired[List[str]]
    merchant_sku_code: NotRequired[str]
    express_number: NotRequired[str]
    is_delivery_late: NotRequired[bool]
    is_delivery_timeout_imminent: NotRequired[bool]
    is_fee_detail: NotRequired[int]


class MerchantOrderInfoResponseDataListGoodsInfo(TypedDict):
    img: Required[str]
    title: Required[str]
    root_category_name: Required[str]
    child_category_name: Required[str]
    specification: Required[str]
    size: Required[str]
    brand_name: Required[str]
    quality: Required[str]
    status: Required[int]


class MerchantOrderInfoResponseDataListFeeDetail(TypedDict):
    total_fees: Required[int]


class MerchantOrderInfoResponseDataListFlawListItem(TypedDict):
    img: Required[str]
    desc: Required[str]


class MerchantOrderInfoResponseDataListItem(TypedDict):
    sell_order_number: Required[str]
    upc: Required[str]
    goods_info: Required[MerchantOrderInfoResponseDataListGoodsInfo]
    status: Required[int]
    sub_status: Required[int]
    status_desc: Required[str]
    sku_min_price: Required[int]
    price: Required[int]
    final_price: Required[int]
    fee_detail: Required[MerchantOrderInfoResponseDataListFeeDetail]
    retrieve_price: Required[int]
    is_free_ship: Required[int]
    free_ship_info: Required[Dict[str, Any]]
    publish_time: Required[str]
    img_list: Required[List[str]]
    flaw_list: Required[List[MerchantOrderInfoResponseDataListFlawListItem]]
    batch_number: Required[str]
    goods_sn: Required[str]
    imei: Required[str]
    buyer_price: Required[int]
    seller_coupon_amount: Required[int]
    full_reduction_amount: Required[int]
    free_shipping_amount: Required[int]
    is_posterior: Required[bool]
    posterior_status: Required[int]
    seller_order_create_time: Required[str]
    buyer_order_pay_time: Required[str]
    merchant_sku_code: Required[str]
    delivery_deadline: Required[str]
    is_delivery: Required[bool]
    delivery_time: Required[str]
    delivery_express_number: Required[str]
    delivery_express_company: Required[str]
    seller_address: Required[str]
    buyer_address: Required[str]
    sku_id: Required[int]
    delivery_type: Required[int]
    buyer_name: Required[str]
    buyer_phone: Required[str]
    buyer_detail_address: Required[str]
    buyer_order_time: Required[str]
    is_margin_deposit: Required[int]
    deposit: Required[str]


class MerchantOrderInfoResponseData(TypedDict):
    total: Required[int]
    list: Required[List[MerchantOrderInfoResponseDataListItem]]


class MerchantOrderInfoResponse(TypedDict):
    data: Required[MerchantOrderInfoResponseData]


class SkuListBindingRequest(TypedDict):
    merchant_sku_code: NotRequired[List[str]]
    start_binding_time: NotRequired[str]
    end_binding_time: NotRequired[str]
    page: NotRequired[int]
    page_size: NotRequired[int]


class SkuListBindingResponseDataListSkuPropertiesItem(TypedDict):
    property_name: Required[str]
    property_value: Required[str]


class SkuListBindingResponseDataListItem(TypedDict):
    sku_id: Required[int]
    title: Required[str]
    property_value: Required[str]
    sku_properties: Required[List[SkuListBindingResponseDataListSkuPropertiesItem]]
    code: Required[str]
    root_category_id: Required[int]
    root_category_name: Required[str]
    middle_category_id: Required[int]
    middle_category_name: Required[str]
    child_category_id: Required[int]
    child_category_name: Required[str]
    brand_id: Required[int]
    brand_name: Required[str]
    spu_id: Required[int]
    merchant_sku_code: Required[str]
    bind_time: Required[str]
    img: Required[str]


class SkuListBindingResponseData(TypedDict):
    total: Required[int]
    list: Required[List[SkuListBindingResponseDataListItem]]


class SkuListBindingResponse(TypedDict):
    data: Required[SkuListBindingResponseData]


class SkuListGeneralRequest(TypedDict):
    child_category_id_list: Required[List[int]]
    page: NotRequired[int]
    page_size: NotRequired[int]
    brand_name: NotRequired[str]
    brand_id: NotRequired[int]
    title: NotRequired[str]
    code: NotRequired[str]
    spu_id: NotRequired[int]
    last_id: NotRequired[int]
    ids: NotRequired[List[int]]
    must_status: NotRequired[int]


class SkuListGeneralResponseDataListSkuPropertiesItem(TypedDict):
    property_name: Required[str]
    property_value: Required[str]


class SkuListGeneralResponseDataListItem(TypedDict):
    sku_id: Required[int]
    title: Required[str]
    property_value: Required[str]
    sku_properties: Required[List[SkuListGeneralResponseDataListSkuPropertiesItem]]
    code: Required[str]
    root_category_id: Required[int]
    root_category_name: Required[str]
    middle_category_id: Required[int]
    middle_category_name: Required[str]
    child_category_id: Required[int]
    child_category_name: Required[str]
    brand_id: Required[int]
    brand_name: Required[str]
    spu_id: Required[int]
    spu_source: Required[str]
    spu_src_orig: Required[str]


class SkuListGeneralResponseData(TypedDict):
    total: Required[int]
    list: Required[List[SkuListGeneralResponseDataListItem]]


class SkuListGeneralResponse(TypedDict):
    data: Required[SkuListGeneralResponseData]


class AddOrderGoodsRequestPropertyListItem(TypedDict):
    id: Required[int]
    name: Required[str]
    property_type: Required[int]
    value: Required[str]


class AddOrderGoodsRequest(TypedDict):
    goods_sn: Required[str]
    title: NotRequired[str]
    brand_id: Required[int]
    l1_category_id: Required[int]
    l2_category_id: NotRequired[int]
    first_img: Required[str]
    general_imgs: Required[List[str]]
    quality: NotRequired[int]
    price: Required[int]
    size: NotRequired[str]
    parts: NotRequired[str]
    code: NotRequired[str]
    remark: NotRequired[str]
    flaw_desc: NotRequired[str]
    flaw_imgs: NotRequired[List[str]]
    fit_id: NotRequired[int]
    support_bargain: NotRequired[int]
    property_list: NotRequired[List[AddOrderGoodsRequestPropertyListItem]]


class AddOrderGoodsResponse(TypedDict):
    status: Required[int]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class GoodsInfoRequest(TypedDict):
    goods_sn: Required[str]


class GoodsInfoResponseData(TypedDict):
    status: Required[int]
    channel_sku_url: Required[str]


class GoodsInfoResponse(TypedDict):
    data: Required[GoodsInfoResponseData]


class UpdatePriceRequest(TypedDict):
    goods_sn: Required[str]
    price: Required[int]


class UpdatePriceResponse(TypedDict):
    status: Required[int]
    req_id: Required[str]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class CancelOrderRequest(TypedDict):
    goods_sn: Required[str]
    type: NotRequired[int]


class CancelOrderResponse(TypedDict):
    status: Required[int]
    req_id: Required[str]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class UpdateSellerBargainRequest(TypedDict):
    goods_sn: Required[str]
    price: Required[int]


class UpdateSellerBargainResponse(TypedDict):
    status: Required[int]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class BargainSuccessRequest(TypedDict):
    goods_sn: Required[str]
    price: Required[int]


class BargainSuccessResponse(TypedDict):
    status: Required[int]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class QueryPropertiesRequest(TypedDict):
    child_category_id: Required[int]


class QueryPropertiesResponseDataListItem(TypedDict):
    id: Required[int]
    name: Required[str]
    property_type: Required[int]
    value_options: Required[str]
    is_required: Required[int]


class QueryPropertiesResponseData(TypedDict):
    list: Required[List[QueryPropertiesResponseDataListItem]]


class QueryPropertiesResponse(TypedDict):
    status: Required[int]
    req_id: Required[str]
    msg: Required[str]
    data: Required[QueryPropertiesResponseData]


class GetBrandIdentifyAbilityRequest(TypedDict):
    l1_category_id: Required[int]
    l2_category_id: NotRequired[int]
    brand_name: Required[str]


class GetBrandIdentifyAbilityResponseDataListItem(TypedDict):
    id: Required[int]
    name: Required[str]


class GetBrandIdentifyAbilityResponseData(TypedDict):
    list: Required[List[GetBrandIdentifyAbilityResponseDataListItem]]


class GetBrandIdentifyAbilityResponse(TypedDict):
    status: Required[int]
    req_id: Required[str]
    msg: Required[str]
    data: Required[GetBrandIdentifyAbilityResponseData]


class CopyOnSaleRequest(TypedDict):
    old_goods_sn: Required[str]
    new_goods_sn: Required[str]
    price: Required[int]


class CopyOnSaleResponse(TypedDict):
    status: Required[int]
    msg: Required[str]
    data: Required[Dict[str, Any]]


class ReferencePriceRequest(TypedDict):
    goods_sn: Required[str]
    order_number: Required[str]
    sku_id: NotRequired[int]
    is_new: NotRequired[int]
    sale_type: NotRequired[int]


class ReferencePriceResponseData(TypedDict):
    platform_min_price: Required[int]
    consign_min_price: Required[int]
    recent_trans_price: Required[int]
    new_market_price: Required[int]
    platform_max_price: Required[int]


class ReferencePriceResponse(TypedDict):
    data: Required[ReferencePriceResponseData]


class RefundListRequest(TypedDict):
    seller_order_number: NotRequired[str]
    refund_number: NotRequired[str]
    in_express_number: NotRequired[str]
    refund_step: NotRequired[int]
    apply_time_start: NotRequired[str]
    apply_time_end: NotRequired[str]
    last_update_start: NotRequired[str]
    last_update_end: NotRequired[str]
    page: NotRequired[int]
    page_size: NotRequired[int]


class RefundListResponseDataListGoodsInfo(TypedDict):
    title: Required[str]
    merchant_sku_code: Required[str]
    sku_id: Required[int]


class RefundListResponseDataListRefundInfo(TypedDict):
    step_name: Required[str]
    refund_step: Required[int]
    apply_reason: Required[str]
    in_express_number: Required[str]


class RefundListResponseDataListItem(TypedDict):
    goods_info: Required[RefundListResponseDataListGoodsInfo]
    refund_info: Required[RefundListResponseDataListRefundInfo]


class RefundListResponseData(TypedDict):
    total: Required[int]
    list: Required[List[RefundListResponseDataListItem]]


class RefundListResponse(TypedDict):
    data: Required[RefundListResponseData]


class RefundConfirmRequest(TypedDict):
    refund_number: Required[str]


class RefundConfirmResponseData(TypedDict):
    result: Required[bool]


class RefundConfirmResponse(TypedDict):
    data: Required[RefundConfirmResponseData]


class RefundBuyerAddressRequest(TypedDict):
    refund_number: Required[str]


class RefundBuyerAddressResponseData(TypedDict):
    address: Required[str]


class RefundBuyerAddressResponse(TypedDict):
    data: Required[RefundBuyerAddressResponseData]


class RefundSuccessRequest(TypedDict):
    refund_number: Required[str]
    return_express_number: Required[str]
    return_express_type: Required[int]


class RefundSuccessResponseData(TypedDict):
    success: Required[bool]


class RefundSuccessResponse(TypedDict):
    data: Required[RefundSuccessResponseData]


class RefundOrderInfoRequest(TypedDict):
    refund_time: NotRequired[str]
    goods_sn: NotRequired[str]
    order_number: NotRequired[List[str]]
    page: NotRequired[int]
    page_size: NotRequired[int]


class RefundOrderInfoResponseDataOrderListItem(TypedDict):
    goods_sn: Required[str]
    sell_order_number: Required[str]
    refund_reason_type_desc: Required[str]
    sell_order_status: Required[str]
    refund_order_status: Required[int]
    buyer_pay_time: Required[str]
    into_time: Required[str]
    imei: Required[str]
    goods_info: Required[Dict[str, Any]]
    price: Required[int]
    refund_price: Required[int]
    refund_confirm_time: Required[str]
    root_determine_types: Required[int]
    refund_determine_time: Required[str]
    goods_belong: Required[int]
    refund_time: Required[str]
    root_determine_option_name: Required[str]
    remark: Required[str]
    refund_seller_express_number: Required[str]
    is_post_inspection_order: Required[str]


class RefundOrderInfoResponseData(TypedDict):
    order_list: Required[List[RefundOrderInfoResponseDataOrderListItem]]


class RefundOrderInfoResponse(TypedDict):
    data: Required[RefundOrderInfoResponseData]

